### ISSUE TITLE
classification example will not perform make

### ISSUE THREAD

**Issue by eladpar-rnd** [bitcraze/aideck-gap8-examples#101]
hey im trying to run the make command with my gap_sdk,
it seems to run smoothly up untill it gets to :
```
/home/eladpar/aideck_phaze2/gap_sdk/tools/autotiler_v3/Emulation/at_api_pmsis.h:206:32: error: storage size of 'default_flash_conf' isn't known
   struct pi_default_flash_conf default_flash_conf;
```
![Screenshot from 2022-07-31 16-32-18](https://user-images.githubusercontent.com/72129770/182028820-1fc43d16-f332-4810-a749-88747208b176.png)

**Comment by knmcguire** [comment]
Hi!

This seems like an GAP sdk issue, and not related to this repository as this just contains examples that depend on that SDK. You should start an issue in Greenwaves Gap_sdk repo on github: https://github.com/GreenWaves-Technologies/gap_sdk

Also make sure to mention there where in their documentation it goes wrong and which version of the sdk you are trying to build.

For the aideck examples, we advise to use the AIdeck docker we made, which the instructions to set it up are in the [aideck tutorial](https://www.bitcraze.io/documentation/tutorials/getting-started-with-aideck/).
